src/main/java/pl/edu/agh/ki/io/models/Friendship.java, src/main/java/pl/edu/agh/ki/io/models/Gender.java, src/main/java/pl/edu/agh/ki/io/models/Peak.java, src/main/java/pl/edu/agh/ki/io/models/PeakCompletion.java, src/main/java/pl/edu/agh/ki/io/models/User.java
Add timestamps to models
Adding unique to fields
Adding nullable false to fields
=> Refactoring

src/main/java/pl/edu/agh/ki/io/config/SecurityConfig.java
Crucial fix, to connect with frontend 
Each second you are reviewing this one frontend developer gets 401/403 on login page, save frontenders - merge the branch
=> fix CORS issues to connect with frontend

src/main/java/pl/edu/agh/ki/io/models/Peak.java, src/main/java/pl/edu/agh/ki/io/models/User.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/Photo.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/Post.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/WallElement.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/WallItem.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/reactions/Reaction.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/reactions/ReactionKey.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/reactions/ReactionType.java
Abstract class wall item to group posts, photos (and in the future trips).
Also added simple reactions model to posts.
For reviewers: One import is deleted because it was unused.
=> Sa 9 Post, Reactions

src/main/java/pl/edu/agh/ki/io/Application.java, src/main/java/pl/edu/agh/ki/io/api/CreateUserRequest.java, src/main/java/pl/edu/agh/ki/io/api/PublicApiController.java, src/main/java/pl/edu/agh/ki/io/api/UserApiController.java, src/main/java/pl/edu/agh/ki/io/api/UserResponse.java, src/main/java/pl/edu/agh/ki/io/cloudstorage/GoogleCloudFileService.java, src/main/java/pl/edu/agh/ki/io/config/PasswordConfig.java, src/main/java/pl/edu/agh/ki/io/config/SecurityConfig.java, src/main/java/pl/edu/agh/ki/io/db/DbInit.java, src/main/java/pl/edu/agh/ki/io/db/GenderRepository.java, src/main/java/pl/edu/agh/ki/io/db/GenderStorage.java, src/main/java/pl/edu/agh/ki/io/db/UserStorage.java, src/main/java/pl/edu/agh/ki/io/models/User.java, src/main/java/pl/edu/agh/ki/io/security/JwtAuthorizationFilter.java, src/main/java/pl/edu/agh/ki/io/security/LoginRequest.java, src/main/java/pl/edu/agh/ki/io/validation/EmailValidator.java, src/main/java/pl/edu/agh/ki/io/validation/PasswordMatches.java, src/main/java/pl/edu/agh/ki/io/validation/PasswordMatchesValidator.java, src/main/java/pl/edu/agh/ki/io/validation/SimpleSqlProtected.java, src/main/java/pl/edu/agh/ki/io/validation/SqlProtectionValidator.java, src/main/java/pl/edu/agh/ki/io/validation/ValidEmail.java, src/main/resources/application.properties
Rejestracja użytkowników. 
Naprawia błąd w konfiguracji 
Usuwa niepotrzebne importy
Dodaje bazową walidację pól na formie rejestracji po stronie backend
=> [Sa-44] rejestracja

src/main/java/pl/edu/agh/ki/io/api/PublicApiController.java, src/main/java/pl/edu/agh/ki/io/db/DbInit.java, src/main/java/pl/edu/agh/ki/io/db/PeakRepository.java, src/main/java/pl/edu/agh/ki/io/db/PeakStorage.java, src/main/java/pl/edu/agh/ki/io/models/Peak.java
* added repository for peaks
* added test data to the database
=> SA-67; added peakRepository

src/main/java/pl/edu/agh/ki/io/db/DbInit.java, src/main/java/pl/edu/agh/ki/io/models/Peak.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/Photo.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/WallItem.java
changed length of about field in peak and content field in wallitem
added photo to peak
added photo_path to photo
=> change varchar lengths, add photo_path field to photo, add photo to peak

src/main/java/pl/edu/agh/ki/io/api/WallItemApiController.java, src/main/java/pl/edu/agh/ki/io/db/DbInit.java, src/main/java/pl/edu/agh/ki/io/db/PhotoRepository.java, src/main/java/pl/edu/agh/ki/io/db/PostRepository.java, src/main/java/pl/edu/agh/ki/io/db/WallItemRepository.java, src/main/java/pl/edu/agh/ki/io/db/WallItemStorage.java, src/main/java/pl/edu/agh/ki/io/models/User.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/Photo.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/Post.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/WallItem.java, src/main/java/pl/edu/agh/ki/io/security/JwtAuthorizationFilter.java, src/main/resources/application.properties
Endpoint do wszystkich wallItems (posty i zdjecia) api/public/wallitems
Tworzenie posta i zdjecia odpowiednio pod api/public/wallitems/post i api/public/wallitems/photo
=> Sa 11 add photos Sa 48 Add posts

src/main/java/pl/edu/agh/ki/io/db/DbInit.java
Added all peaks from Crown of Polish Mountains list.
=> SA-110; added all peaks

src/main/java/pl/edu/agh/ki/io/api/PeakPostsApiController.java, src/main/java/pl/edu/agh/ki/io/db/DbInit.java, src/main/java/pl/edu/agh/ki/io/db/PeakPostsRepository.java, src/main/java/pl/edu/agh/ki/io/db/PeakPostsStorage.java, src/main/java/pl/edu/agh/ki/io/models/Peak.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/PeakPost.java
Dałem to pod endpointem szczytów bo chyba tylko stamtąd będziemy chcieli je dostawać - wrzucacie peakid i dostajecie wszystkie posty do niego, jeśli zrobicie POST na tym to się doda nowy post pod tym szczytem
=> Sa 121 123 peak post

src/main/java/pl/edu/agh/ki/io/api/UserApiController.java, src/main/java/pl/edu/agh/ki/io/db/DbInit.java, src/main/java/pl/edu/agh/ki/io/db/UserStorage.java
Dodałam endpoint do pobierania usera po id, bo przyda się na froncie.
Proponuję najpierw to zmergować, a dopiero potem tamtego PR.
=> Endpoint for user

src/main/java/pl/edu/agh/ki/io/api/CreateUserRequest.java, src/main/java/pl/edu/agh/ki/io/validation/PasswordValidator.java, src/main/java/pl/edu/agh/ki/io/validation/ValidPassword.java, src/main/resources/application.properties
prosta walidacja długości hasła. Może być również uzupełniona innymi warunkami poprawności
=> [SA-128] basic password validation

src/main/java/pl/edu/agh/ki/io/db/DbInit.java, src/main/java/pl/edu/agh/ki/io/models/Peak.java
Dodałam do modelu szczytu szerokość i długość geograficzną i uzupełniłam te dane we wszystkich szczytach (działa z frontendem i mapki się już wyświetlają).
=> SA-115; added localization to peak model

src/main/java/pl/edu/agh/ki/io/security/JwtAuthenticationFilter.java
poprawia bug SA-132. Dodaje user id w respoce body po udanemu zalogowaniu się
=> [SA-132] add user id to login response

src/main/java/pl/edu/agh/ki/io/api/PeakCompletionsApiController.java, src/main/java/pl/edu/agh/ki/io/db/PeakCompletionsRepository.java, src/main/java/pl/edu/agh/ki/io/db/PeakCompletionsStorage.java
dodałem endpointy na pobieranie pierwszej osoby na szczycie i liczby osób które zdobyły dany szczyt
=> [SA-120;SA-118] add endpoint to obtain peak statistics

src/main/java/pl/edu/agh/ki/io/validation/PasswordValidator.java
Walidacja hasla taka jak na froncie
=> Sa 131 password validation

src/main/java/pl/edu/agh/ki/io/api/PeaksApiController.java, src/main/java/pl/edu/agh/ki/io/api/models/PeakResponse.java, src/main/java/pl/edu/agh/ki/io/db/PeakCompletionsRepository.java, src/main/java/pl/edu/agh/ki/io/db/PeakCompletionsStorage.java
Zmniejszylem ilosc info ktore daje endpoint z peakami - tylko pola podstawowe, bez relacji
Dodane pole completed ktore mowi czy dany uzytkownik zdobyl dany szczyt
=> Sa 157 endpoint for peak completion

src/main/java/pl/edu/agh/ki/io/api/PeaksApiController.java
Dodałam informacje o zdobyciu szczytu do endpointu z listą szczytów, bo przyda się też na froncie.
=> Info about completion of a peak in list of peaks

src/main/java/pl/edu/agh/ki/io/api/FriendshipsApiController.java, src/main/java/pl/edu/agh/ki/io/api/UserApiController.java, src/main/java/pl/edu/agh/ki/io/db/FriendshipRepository.java, src/main/java/pl/edu/agh/ki/io/db/FriendshipStorage.java, src/main/java/pl/edu/agh/ki/io/models/Friendship.java
Przypominajka - w bazie na jeden friendship beda dwa rekordy zeby latwiej sie szukalo i zwracalo
0 - pending friendship 1 - accepted friendship
/api/public/{userid}/add - wysyla zaproszenie do usera z userid, jesli juz on nam je wyslal to je akceptuje
/api/public/{userid}/accept - akceptuje zaproszenie od usera z userid
/api/public/{userid}/reject - usuwa zaproszenie od usera z userid 
/api/public/{userid}/remove - usuwa znajomosc
Zmienie jeszcze to co jest zwracane zeby nie bylo tak duzo danych tam ale endpointy juz sa gotowe wiec mozecie sprawdzic
=> Sa 6 adding friends

src/main/java/pl/edu/agh/ki/io/api/PeakCompletionsApiController.java, src/main/java/pl/edu/agh/ki/io/db/DbInit.java
Dodałam endpoint do pobierania średniego czasu zdobycia szczytu i dodałam kilka przykładowych danych, żeby było z czego obliczać.
Później można zamienić ten endpoint na metodę jak już wszystkie statystyki będą razem zwracane.
=> Average time of peak completions

src/main/java/pl/edu/agh/ki/io/api/PeakCompletionsApiController.java, src/main/java/pl/edu/agh/ki/io/api/PeaksApiController.java, src/main/java/pl/edu/agh/ki/io/api/models/PeakCompletionResponse.java, src/main/java/pl/edu/agh/ki/io/api/models/PeakResponse.java, src/main/java/pl/edu/agh/ki/io/api/models/UserResponse.java, src/main/java/pl/edu/agh/ki/io/api/providers/PeakStatisticsProvider.java, src/main/java/pl/edu/agh/ki/io/db/PeakCompletionsRepository.java, src/main/java/pl/edu/agh/ki/io/db/PeakCompletionsStorage.java
skończyłem statystyki. dodałem statystyki do zapytania o szczyty
=> [Sa-117; SA-119] statistics

src/main/java/pl/edu/agh/ki/io/api/UserApiController.java, src/main/java/pl/edu/agh/ki/io/db/UserStorage.java, src/main/java/pl/edu/agh/ki/io/models/UserPage.java
Podmienienie endpointa /users na zwracający spaginowanych userów
=> Paginate users

src/main/java/pl/edu/agh/ki/io/api/PeaksApiController.java, src/main/java/pl/edu/agh/ki/io/api/providers/PeakStatisticsProvider.java, src/main/java/pl/edu/agh/ki/io/db/PeakCompletionsRepository.java, src/main/java/pl/edu/agh/ki/io/db/PeakCompletionsStorage.java
@AlexMaz99, pomyślałem że statystyki we wszystkich postach trochę ułatwią życie na froncie. Czy wywalić to?
=> [SA-198] stats fix

src/main/java/pl/edu/agh/ki/io/api/UserApiController.java, src/main/java/pl/edu/agh/ki/io/api/models/FriendshipRequestResponse.java, src/main/java/pl/edu/agh/ki/io/db/DbInit.java, src/main/java/pl/edu/agh/ki/io/db/FriendshipRepository.java, src/main/java/pl/edu/agh/ki/io/db/FriendshipStorage.java, src/main/java/pl/edu/agh/ki/io/db/UserRepository.java, src/main/java/pl/edu/agh/ki/io/db/UserStorage.java
poszukiwanie użytkowników tylko po stronie backu i z paginacja.
`searchTerm` dostaje się w query params tak jak pageNumber i pageSize
=> Sa 200 search users

src/main/java/pl/edu/agh/ki/io/api/models/PeakPostResponse.java, src/main/java/pl/edu/agh/ki/io/api/models/PhotoResponse.java, src/main/java/pl/edu/agh/ki/io/api/models/PostResponse.java
Dodałam parę rzeczy, które są potrzebne na froncie
=> added user, longitude and latitude to posts responses

src/main/java/pl/edu/agh/ki/io/api/FriendshipsApiController.java, src/main/java/pl/edu/agh/ki/io/api/models/FriendshipRequest.java, src/main/java/pl/edu/agh/ki/io/models/Friendship.java
=> Refactor friendship

src/main/java/pl/edu/agh/ki/io/api/PeakPostsApiController.java, src/main/java/pl/edu/agh/ki/io/api/PhotoApiController.java, src/main/java/pl/edu/agh/ki/io/api/PostApiController.java, src/main/java/pl/edu/agh/ki/io/api/models/CreatePostRequest.java, src/main/java/pl/edu/agh/ki/io/api/models/PhotoRequest.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/PeakPost.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/Photo.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/Post.java, src/main/resources/application.properties
Dodałam współrzędne do endpointów, które tworzą posty. Jak ich nie ma, to w bazie zapisuje się 0.0, ale tak było już wcześniej.
=> added latitude and longitude to create post request

src/main/java/pl/edu/agh/ki/io/api/FriendshipsApiController.java
=> make it impossible to create a couple of friendship requests at the same time

src/main/java/pl/edu/agh/ki/io/api/PeakPostsApiController.java, src/main/java/pl/edu/agh/ki/io/api/models/CreatePostRequest.java, src/main/java/pl/edu/agh/ki/io/api/models/PeakPostResponse.java, src/main/java/pl/edu/agh/ki/io/db/PeakPostsStorage.java, src/main/java/pl/edu/agh/ki/io/models/wallElements/PeakPost.java
Dodałam zdjęcie do postu ze szczytem. @piotrpolec  mógłbyś to zmienić w zdalnej bazie?
=> added photo to peakPost

pom.xml, src/main/java/pl/edu/agh/ki/io/api/ChatApiController.java, src/main/java/pl/edu/agh/ki/io/api/models/SendMessageRequest.java, src/main/java/pl/edu/agh/ki/io/api/models/SetSeenRequest.java, src/main/java/pl/edu/agh/ki/io/config/ChatConfig.java, src/main/java/pl/edu/agh/ki/io/config/SecurityConfig.java, src/main/java/pl/edu/agh/ki/io/db/ChatMessageRepository.java, src/main/java/pl/edu/agh/ki/io/db/ChatMessageStorage.java, src/main/java/pl/edu/agh/ki/io/models/ChatMessage.java
ktoś z frontu musis to przetestować bo ja nie mam jak :)
=> [WIP] chat
